<?php

namespace AppBundle\Repository;

/**
 * ChefProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChefProjetRepository extends \Doctrine\ORM\EntityRepository
{
}
