google.maps.__gjsload__('stats', function(_){'use strict';var f3=function(a,b,c){var d=[];_.zc(a,function(a,c){d.push(c+b+a)});return d.join(c)},g3=function(a,b,c,d){var e={};e.host=window.document.location&&window.document.location.host||window.location.host;e.v=a;e.r=Math.round(1/b);c&&(e.client=c);d&&(e.key=d);return e},oea=function(a){var b={};_.zc(a,function(a,d){b[(0,window.encodeURIComponent)(d)]=(0,window.encodeURIComponent)(a).replace(/%7C/g,"|")});return f3(b,":",",")},pea=function(){this.j=new _.HB;this.N=0},h3=function(a,b){var c=
new window.Image,d=a.N++;a.j.set(d,c);c.onload=c.onerror=function(){c.onload=c.onerror=_.ta;a.j.remove(d)};c.src=b},qea=function(a,b,c,d){var e=_.R.j[23],f=_.R.j[22];this.W=a;this.$=b;this.na=null!=e?e:500;this.R=null!=f?f:2;this.T=c;this.S=d;this.N=new _.HB;this.j=0;this.O=_.Ca();i3(this)},i3=function(a){window.setTimeout(function(){rea(a);i3(a)},Math.min(a.na*Math.pow(a.R,a.j),2147483647))},j3=function(a,b,c){a.N.set(b,c)},rea=function(a){var b=g3(a.$,a.T,a.S,void 0);b.t=a.j+"-"+(_.Ca()-a.O);a.N.forEach(function(a,
d){var e=a();0<e&&(b[d]=Number(e.toFixed(2))+(_.Ok()?"":"-if"))});a.W.j({ev:"api_snap"},b);++a.j},k3=function(a,b,c,d,e){this.S=a;this.W=b;this.R=c;this.N=d;this.O=e;this.j=new _.HB;this.T=_.Ca()},l3=function(a,b){this.R=b;this.O=a+"/maps/gen_204";this.N=new pea},m3=function(){this.j=new _.HB},sea=function(a){var b=0,c=0;a.j.forEach(function(a){b+=a.nr;c+=a.Oq});return c?b/c:0},n3=function(a,b,c,d,e){this.T=a;this.W=b;this.S=c;this.O=d;this.R=e;this.N={};this.j=[]},o3=function(a,b,c,d){this.O=a;_.H.bind(this.O,
"set_at",this,this.R);_.H.bind(this.O,"insert_at",this,this.R);this.T=b;this.W=c;this.S=d;this.N=0;this.j={};this.R()},p3=function(){this.j={}},tea=function(){this.j=[];this.N=[]},q3=function(a,b,c){this.j=a;this.N=b;this.O=c},uea=function(a,b){a.j.j.push(b);var c=a.N,d=_.pb(b),c=c.j;d in c||(c[d]=0);++c[d];d=a.j;if(d.j.length+d.N.length>a.O){c=a.j;d=c.N;c=c.j;if(!d.length)for(;c.length;)d.push(c.pop());(d=d.pop())&&a.N.remove(d)}},r3=function(a,b){this.S=new q3(new tea,new p3,100);this.N=null;this.wa=
[];this.R=a;_.H.bind(a,"insert_at",this,this.bf);_.H.bind(a,"set_at",this,this.bf);_.H.bind(a,"remove_at",this,this.bf);this.bf();this.j=0;this.oa=b;this.O=0},s3=function(){this.N=_.Xe(_.R);var a;_.Kj()?(a=_.Oe(_.R).j[11],a=null!=a?a:""):a=_.jx;this.j=new l3(a,_.ii);new o3(_.ei,(0,_.u)(this.j.j,this.j),_.Mf,!!this.N);a=_.Te(_.bf());this.T=a.split(".")[1]||a;_.hi&&(this.O=new qea(this.j,this.T,this.na,this.N));this.W={};this.S={};this.R={};this.$={};this.na=_.We()};
k3.prototype.$=function(a,b){var c=_.sa(b)?b:1;this.j.isEmpty()&&window.setTimeout((0,_.u)(function(){var a=g3(this.W,this.R,this.N,this.O);a.t=_.Ca()-this.T;var b=this.j;_.IB(b);for(var c={},g=0;g<b.j.length;g++){var h=b.j[g];c[h]=b.oa[h]}_.GA(a,c);this.j.clear();this.S.j({ev:"api_maprft"},a)},this),500);c=this.j.get(a,0)+c;this.j.set(a,c)};
l3.prototype.j=function(a,b){var c=b||{},d=_.wj().toString(36);c.src="apiv3";c.token=this.R;c.ts=d.substr(d.length-6);a.cad=oea(c);c=f3(a,"=","&");h3(this.N,this.O+"?target=api&"+c)};l3.prototype.S=function(a){h3(this.N,a)};m3.prototype.N=function(a,b,c){this.j.set(_.pb(a),{nr:b,Oq:c})};n3.prototype.$=function(a){this.N[a]||(this.N[a]=!0,this.j.push(a),2>this.j.length&&_.aB(this,this.na,500))};
n3.prototype.na=function(){for(var a=g3(this.W,this.S,this.O,this.R),b=0,c;c=this.j[b];++b)a[c]="1";a.hybrid=+((_.ok()||!_.nk())&&_.nk());this.j.length=0;this.T.j({ev:"api_mapft"},a)};o3.prototype.R=function(){for(var a;a=this.O.removeAt(0);){var b=a.xq;a=a.timestamp-this.W;++this.N;this.j[b]||(this.j[b]=0);++this.j[b];if(20<=this.N&&!(this.N%5)){var c={};c.s=b;c.sr=this.j[b];c.tr=this.N;c.te=a;c.hc=this.S?"1":"0";this.T({ev:"api_services"},c)}}};p3.prototype.remove=function(a){a=_.pb(a);var b=this.j;a in b&&(--b[a],b[a]||delete b[a])};q3.prototype.contains=function(a){return!!this.N.j[_.pb(a)]};_.w(r3,_.J);_.t=r3.prototype;_.t.bf=function(){_.G(this.wa,_.H.removeListener);this.wa.length=0;var a=this.wa,b=(0,_.u)(this.Ng,this);this.R.forEach(function(c){a.push(_.H.addListener(c.data,"insert",b))});b()};
_.t.Ng=function(){var a=this.get("bounds");if(this.get("projection")&&a&&this.N){var b={};this.R.forEach((0,_.u)(function(c){c.data.forEach((0,_.u)(function(c){var d=c.rawData;if(0==(""+d.layer).indexOf(this.N.substr(0,5))&&d.features){c=d.id.length;for(var e=_.jJ(d.id),d=d.features,k=0,n;n=d[k];k++){var p=n.id,q;a:{q=n;if(!q.latLngCached){var r=q.a;if(!r){q=null;break a}var v=new _.M(r[0],r[1]),r=e,v=[v.x,v.y],y=(1<<c)/8388608;v[0]/=y;v[1]/=y;v[0]+=r.qa;v[1]+=r.pa;v[0]/=8388608;v[1]/=8388608;r=new _.M(v[0],
v[1]);v=this.get("projection");q.latLngCached=v&&v.fromPointToLatLng(r)}q=q.latLngCached}q&&a.contains(q)&&(b[p]=n)}}},this))},this));var c=this.S,d;for(d in b)c.contains(d)||(++this.j,uea(c,d));!this.O&&this.j&&(this.O=_.aB(this,this.Ko,0))}else _.aB(this,this.Ng,1E3)};_.t.Ko=function(){this.O=0;this.j&&(_.yl(this.oa,"smni",this.j),this.j=0)};_.t.mapType_changed=function(){var a=this.get("mapType");this.N=a&&a.$f};_.t.bounds_changed=function(){this.Ng()};_.t=s3.prototype;_.t.En=function(a,b){var c=new r3(b,a);c.bindTo("mapType",a.__gm);c.bindTo("zoom",a);c.bindTo("bounds",a);c.bindTo("projection",a)};_.t.Zn=function(a){a=_.pb(a);this.W[a]||(this.W[a]=new n3(this.j,this.T,this.na,this.N));return this.W[a]};_.t.Xn=function(a){a=_.pb(a);this.S[a]||(this.S[a]=new k3(this.j,this.T,1,this.N));return this.S[a]};_.t.qf=function(a){if(this.O){this.R[a]||(this.R[a]=new _.NC,j3(this.O,a,function(){return b.od()}));var b=this.R[a];return b}};
_.t.Wn=function(a){if(this.O){this.$[a]||(this.$[a]=new m3,j3(this.O,a,function(){return sea(b)}));var b=this.$[a];return b}};var vea=new s3;_.ic("stats",vea);});
